package integration

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"database/sql"
	"encoding/pem"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	_ "modernc.org/sqlite"
)

// TestEgressMITMRecordsBody end-to-ends the Phase 2 MITM path: boot
// shield-agent with an autogenerated CA, point at a local HTTPS upstream
// (using the CA's trust configured on the client side), fire a decrypted
// request, and assert the row in egress_logs carries a real prompt_hash,
// model field, and PII flags.
func TestEgressMITMRecordsBody(t *testing.T) {
	egressPort := freePort(t)
	monitorPort := freePort(t)

	// Upstream pretending to be OpenAI — responds with a JSON body that
	// contains a model field, so the content tagger fills in resp.Model.
	upstream := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		io.WriteString(w, `{"id":"chatcmpl-1","model":"gpt-4o","object":"chat.completion"}`)
	}))
	defer upstream.Close()

	upstreamHost, upstreamPort := mustSplitHostPort(t, upstream.URL)

	dir := t.TempDir()
	dbPath := filepath.Join(dir, "egress.db")
	keysPath := filepath.Join(dir, "keys.yaml")
	_ = os.WriteFile(keysPath, []byte("keys: []\n"), 0o600)
	caCert := filepath.Join(dir, "ca.pem")
	caKey := filepath.Join(dir, "ca.key")
	configPath := filepath.Join(dir, "shield-agent.yaml")
	configYAML := fmt.Sprintf(`server:
  monitor_addr: "127.0.0.1:%d"
security:
  mode: "open"
  key_store_path: "%s"
logging:
  level: "error"
  format: "text"
telemetry:
  enabled: false
  endpoint: "http://localhost:8080"
  batch_interval: 60
  epsilon: 1.0
storage:
  db_path: "%s"
  retention_days: 30
egress:
  enabled: true
  listen: "127.0.0.1:%d"
  policy_mode: "warn"
  mitm_hosts: ["%s"]
  ca_cert: "%s"
  ca_key: "%s"
  ca_auto_generate: true
  leaf_cache_ttl_min: 10
  hash_chain:
    enabled: true
    algorithm: "sha256"
  pii_scrub:
    enabled: true
    redaction_mode: "mask"
  content_tagging:
    enabled: true
  middlewares:
    - name: policy
      enabled: true
    - name: compliance
      enabled: true
    - name: egress_log
      enabled: true
`, monitorPort, keysPath, dbPath, egressPort, upstreamHost, caCert, caKey)
	_ = os.WriteFile(configPath, []byte(configYAML), 0o600)

	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, sharedBin, "--config", configPath, "egress")
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard
	// MITM target is a loopback httptest server, so the SSRF guard has
	// to let us in. Production deployments never set this.
	cmd.Env = append(os.Environ(),
		"SHIELD_AGENT_TEST_ALLOW_LOOPBACK=1",
		"SHIELD_AGENT_TEST_UPSTREAM_SKIP_VERIFY=1",
	)
	if err := cmd.Start(); err != nil {
		t.Fatalf("start egress: %v", err)
	}
	defer func() {
		_ = cmd.Process.Kill()
		_ = cmd.Wait()
	}()

	waitForListener(t, fmt.Sprintf("127.0.0.1:%d", egressPort))

	// Client trust store: use the autogenerated CA.
	caPEM, err := os.ReadFile(caCert)
	if err != nil {
		t.Fatalf("read ca: %v", err)
	}
	block, _ := pem.Decode(caPEM)
	if block == nil {
		t.Fatalf("ca not a PEM block")
	}
	caX509, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		t.Fatalf("parse ca: %v", err)
	}
	pool := x509.NewCertPool()
	pool.AddCert(caX509)

	proxyURL, _ := url.Parse(fmt.Sprintf("http://127.0.0.1:%d", egressPort))
	client := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyURL(proxyURL),
			TLSClientConfig: &tls.Config{
				RootCAs:    pool,
				ServerName: upstreamHost,
			},
		},
		Timeout: 10 * time.Second,
	}

	// Use the upstream's TLS-terminated URL but route via the proxy:
	// the request is `GET https://<upstreamHost>:<upstreamPort>/chat`.
	target := fmt.Sprintf("https://%s:%s/v1/chat/completions", upstreamHost, upstreamPort)
	req, _ := http.NewRequest(http.MethodPost, target,
		strings.NewReader(`{"messages":[{"role":"user","content":"my phone 010-1234-5678"}]}`))
	req.Header.Set("Content-Type", "application/json")
	resp, err := client.Do(req)
	if err != nil {
		t.Fatalf("proxied MITM request: %v", err)
	}
	body, _ := io.ReadAll(resp.Body)
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("status = %d body = %q", resp.StatusCode, body)
	}

	// Give the LogWriter a moment to persist.
	waitForRow(t, dbPath, 3*time.Second)

	db, err := sql.Open("sqlite", dbPath+"?_journal_mode=WAL&_busy_timeout=5000")
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	defer db.Close()

	var (
		provider, method, protocol, promptHash, model, contentClass string
		piiDetected, piiScrubbed, aiGenerated                       bool
	)
	scanErr := db.QueryRow(`SELECT provider, method, protocol, prompt_hash, model, content_class,
       pii_detected, pii_scrubbed, ai_generated_tag
FROM egress_logs ORDER BY id DESC LIMIT 1`).Scan(
		&provider, &method, &protocol, &promptHash, &model, &contentClass,
		&piiDetected, &piiScrubbed, &aiGenerated)
	if scanErr != nil {
		t.Fatalf("scan row: %v", scanErr)
	}

	if protocol != "mitm" {
		t.Errorf("protocol = %q, want mitm", protocol)
	}
	if promptHash == "" {
		t.Error("prompt_hash empty — compliance middleware did not run")
	}
	if model != "gpt-4o" {
		t.Errorf("model = %q, want gpt-4o (content tagger)", model)
	}
	if contentClass != "ai_generated" {
		t.Errorf("content_class = %q, want ai_generated", contentClass)
	}
	if !aiGenerated {
		t.Error("ai_generated_tag should be true")
	}
	if !piiDetected {
		t.Error("pii_detected should be true (phone number in prompt)")
	}
	if !piiScrubbed {
		t.Error("pii_scrubbed should be true")
	}
	_ = method
	_ = provider
}

func mustSplitHostPort(t *testing.T, rawURL string) (string, string) {
	t.Helper()
	u, err := url.Parse(rawURL)
	if err != nil {
		t.Fatalf("parse upstream url: %v", err)
	}
	host, port, err := net.SplitHostPort(u.Host)
	if err != nil {
		t.Fatalf("split upstream: %v", err)
	}
	return host, port
}
